# Header
menu:
  首页: /
  关于我们: /about
  我们的项目: /projects
  最近动态: /archives
  特别鸣谢: /thanks
  友情链接: /friends

# Content
excerpt_link: 阅读全文

# MIIT ICP/IP/DOMAIN
beian: 
  enable: false
  number: 
  url: https://beian.miit.gov.cn/

# Miscellaneous
favicon: /rs/logo.png
webclip: /images/webclip
brand:   /images/brand.svg

# Jumbotron video & Hero image & Swiper
## Jumbotron video
video: 
  overlay: false
  path: /images/movie/
## Hero image
hero: 
  image: /rs/banner.png
## Swiper
## https://github.com/nolimits4web/swiper
swiper: 
  enable: false

# Toc
## https://github.com/tscanlin/tocbot
toc: true

# Slogan
slogan: 
  primary: 欢迎来到花枫工作室
  secondary: 以社区为发展根基，以创新促社区发展
  archives: 这里可以看到我们最近的动态！
  pages: 如果你看到了这句话，那么你就看到了这句话。
  posts: 如果你看到了这句话，那么你就看到了这句话。

# Library
libs:
  feather: /libs/feather/feather.min.js # V4.29.0
  lazysizes: /libs/lazysizes/lazysizes.min.js
  tocbot: /libs/tocbot/tocbot.min.js
  swiper: 
    css: /libs/swiper/swiper-bundle.min.css
    js:  /libs/swiper/swiper-bundle.min.js